# Generated by Django 4.2.4 on 2024-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0008_alter_appointments_cancelled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='canceled_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
