# Generated by Django 4.2.4 on 2024-04-07 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0010_therapistavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time_slot',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(17, 0), '05:00 PM')], null=True),
        ),
    ]
