# Generated by Django 4.2.4 on 2024-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0020_paymentp_purchased_items_delete_spects'),
    ]

    
