# Generated by Django 4.2.4 on 2024-04-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0021_delete_spects'),
    ]

    