# Generated by Django 4.2.4 on 2024-04-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IrisGlowApp', '0022_delete_spects'),
    ]

    
